# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b7e44c98802efb3b8404bfc42a02501a4035e80f8318fb898aad80633b1b082c4d9d739a8b55dc771bbe68f82894b8ef6b6139a6628a2f6c671b18f6ee74edd

test:
  secret_key_base: 5d0dcf41e6320b52dfef8c433d8eccc98b15c598c7977e7039001eb2b2bfbab7a7c0e613d69cb34501d446c349c4f6283ba070405d60839bef217c2725caa256

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
